### ISSUE TITLE
The response from item http API isn't sorted

### ISSUE THREAD

**Issue by lordfriend** [irohalab/mira-resource-indexer#42]
I've observed that the HTTP API doesn't return sorted response. 
A search result should be sorted by item's timestamp in descending order.

Besides, to reduce the burden of service, any response items should limited to a configured max count with a default 100 max items count.

**Comment by acgotaku** [comment]
OK, we only show the first 100 result? Or we can use page=2 parameters?

**Comment by lordfriend** [comment]
It is not necessary to show all the match search results because the user only needs to catch the best and most recent match.
