### ISSUE TITLE
Some pages failed to scrap when last queue is partially finished during a container restart

### ISSUE THREAD

**Issue by lordfriend** [irohalab/mira-resource-indexer#69]
Currently, the indexer will queue all sub-tasks in memory. when the queue is partially finished, Restart the process will result in the undetermined state for the current list page. During the next time scraping, the current list page may change, some unfinished detail pages may go to the next list page.
In this case. since the current page is partially finished, the next list page will be scrapped.
The result is some pages will be missed.

**Comment by EverettSummer** [comment]
Fixed after we rewrite the task queue. now the task queue is in mongodb
